name: Backend Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install pipenv
      - run: sudo apt-get update && sudo apt-get install -y python3-dev build-essential
      - run: pipenv install --dev --skip-lock
      - run: pipenv run flake8
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install pipenv
      - run: sudo apt-get update && sudo apt-get install -y python3-dev build-essential
      - run: pipenv install --dev --skip-lock
      - run: pipenv run test